USE DATABASE COVID19_EPIDEMIOLOGICAL_DATA;

SELECT COUNT(*) AS total_rows,
MIN(DATE) AS earliest,
MAX(DATE) AS latest,
COUNT(DISTINCT COUNTRY_REGION) AS countries
FROM PUBLIC.JHU_COVID_19;

SELECT COUNT_IF(CASES IS NULL) AS null_cases,
COUNT_IF(DATE IS NULL) AS null_dates,
COUNT_IF(COUNTRY_REGION IS NULL) AS null_country
FROM PUBLIC.JHU_COVID_19;

SELECT CASE_TYPE, COUNT(*) AS rows_ FROM PUBLIC.JHU_COVID_19
GROUP BY CASE_TYPE;

SELECT COUNTRY_REGION, DATE,
SUM(CASE WHEN CASE_TYPE = 'Confirmed' THEN CASES ELSE 0 END) AS confirmed,
SUM(CASE WHEN CASE_TYPE = 'Deaths' THEN CASES ELSE 0 END) AS deaths,
SUM(CASE WHEN CASE_TYPE = 'Recovered' THEN CASES ELSE 0 END) AS recovered,
SUM(CASE WHEN CASE_TYPE = 'Active' THEN CASES ELSE 0 END) AS active
FROM PUBLIC.JHU_COVID_19
GROUP BY COUNTRY_REGION, DATE;