USE DATABASE COVID_PROJECT;

SELECT * FROM (
  SELECT COUNTRY_REGION, DATE, CASES FROM COVID_ENRICHED
)
MATCH_RECOGNIZE (
  PARTITION BY COUNTRY_REGION
  ORDER BY DATE
  MEASURES
    FIRST(DATE) AS spike_start,
    LAST(DATE) AS spike_end,
    COUNT(*) AS days_in_spike
  PATTERN (RISE{3,})
  DEFINE
    RISE AS CASES > LAG(CASES)
)
ORDER BY days_in_spike DESC;