USE DATABASE COVID_PROJECT;

SELECT * FROM (
  SELECT COUNTRY_REGION, DATE, CASES,
         CASES - LAG(CASES) OVER (PARTITION BY COUNTRY_REGION ORDER BY DATE) AS daily_new_cases
  FROM COVID_ENRICHED
)
MATCH_RECOGNIZE (
  PARTITION BY COUNTRY_REGION
  ORDER BY DATE
  MEASURES
    FIRST(DATE) AS spike_start,
    LAST(DATE) AS spike_end,
    COUNT(*) AS days_accelerating
  PATTERN (ACCELERATE{3,})
  DEFINE
    ACCELERATE AS daily_new_cases > LAG(daily_new_cases)
)
ORDER BY days_accelerating DESC
LIMIT 30;