USE DATABASE COVID_PROJECT;
USE SCHEMA PUBLIC;

ALTER TABLE COVID_ENRICHED CLUSTER BY (COUNTRY_REGION, DATE);

CREATE OR REPLACE VIEW mv_country_daily AS
SELECT COUNTRY_REGION, DATE, "cases_per_100k", "deaths_per_100k" FROM COVID_ENRICHED;

SELECT COUNTRY_REGION, DATE, "cases_per_100k", "deaths_per_100k" FROM COVID_ENRICHED
WHERE COUNTRY_REGION = 'Lithuania'
ORDER BY DATE;

ALTER WAREHOUSE COMPUTE_WH SET RESOURCE_MONITOR = COVID_MONITOR;

SHOW WAREHOUSES;